name: Build the template
on:
  push:
    branches:
      - main
jobs:
  build_sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: godwingrs22/setup-sam@v2.0
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     aws-region: us-east-2
      # Build inside Docker containers
      # - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      # - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
    permissions: {}
